### ISSUE TITLE
Proceedings Paper: Almost finished, please respond to comments

### ISSUE THREAD

**Issue by hagenaue** [NCBI-Hackathons/Network_SNPs#18]
Greetings gentleman,
I filled in all of the blank sections in our Proceedings paper. I think it is basically ready to go except for...
1) A description of how HotNet2 was integrated into the pipeline and example output.
2) Various simple questions/suggested edits that require responses (in red).
Perhaps each of you you can reply to this message with your initials after you read over the manuscript and provide edits? That way it will be clear when we can forward the final copy to Ben.
Cheers,
Megan

**Comment by ffrancis** [comment]
Good job! The manuscript looks much better now.

I have updated the results section for HotNet2 and have made few minor
revisions else where.

Regards,

Felix

**Comment by graphanalytics** [comment]
Hi Felix,

Can you please test the "sample_run.sh" in the network instance and see if
you can help Eric fix the problem...?
I ran the test this morning, but it stops with the "could not run" error
when it tries to run hotnet2.
If you could check the executed command and provide any inputs to Eric
regarding any possible solution, I would greatly appreciate that.

Thanks,
Vijay

**Comment by nyetsche** [comment]
Is the code you're running consistent with what's in Github? Because https://github.com/NCBI-Hackathons/Network_SNPs/blob/master/meta-net-var.py#L299 (where the error comes from) should also output the class names for it fails. But instead you just have a blank line after 'could not run'.

**Comment by graphanalytics** [comment]
Yes, the code is the last pull from github.

**Comment by graphanalytics** [comment]
Hello Vijay,

I tested the "sample_run.sh" that we have on github.

I am not sure if the error message "Could not run:" is related to Hotnet2
since it seems to have run successfully and the output files were written
to the expected path (/home/ubuntu/trial/outdir/Hotnet2/delta_0.1/).

I agree with Matt in that you would expect the class name for any specific
analyzer that has an issue (according to meta-net-var.py).

Ref: line 299

print "Could not run:" + ",".join(a.**class**.**name**+" is
missing:"+",".join(a.missing(possible))
for a in analyzers if not a.can_run_with(possible))

Are we getting the intended output files for NetworkX and FunSeq?

Felix

**Comment by graphanalytics** [comment]
Manuscript complete
